# Generated by Django 2.2.12 on 2020-06-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(height_field=100, upload_to='images/', width_field=100),
        ),
    ]
